import {createHash,randomBytes,scrypt as rawScrypt,timingSafeEqual} from "node:crypto";import {promisify} from "node:util";import {query,queryOne} from "./db";
import {ensureIntroductoryCredits} from "./credits";
const scrypt=promisify(rawScrypt),sessionDays=30;
const digest=(v:string)=>createHash("sha256").update(v).digest("hex");
const normalizeEmail=(v:string)=>v.trim().toLowerCase();
const challengeMinutes=30;
async function passwordHash(password:string,salt:string){return (await scrypt(password,salt,64)) as Buffer;}
export interface AccountUser{id:string;status:string;displayName:string|null;preferredLocale:string;timezone:string;email:string;emailVerificationStatus:string;createdAt:string}
export function parseSessionCookie(header:string|undefined){if(!header)return null;for(const part of header.split(";")){const [k,...rest]=part.trim().split("=");if(k==="dende_session")return decodeURIComponent(rest.join("="));}return null;}
export function sessionCookie(token:string,secure=false){return `dende_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${sessionDays*86400}${secure?"; Secure":""}`;}
export function clearSessionCookie(secure=false){return `dende_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${secure?"; Secure":""}`;}
export async function createAccount(input:{email:string;password:string;displayName?:string|null;userAgent?:string|null;ipAddress?:string|null}){const email=normalizeEmail(input.email);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Enter a valid email address.");if(input.password.length<12)throw new Error("Password must contain at least 12 characters.");const salt=randomBytes(16).toString("hex"),hash=await passwordHash(input.password,salt);const client=await (await import("./db")).pool.connect();try{await client.query("BEGIN");const u=(await client.query(`INSERT INTO accounts.users(display_name) VALUES($1) RETURNING id,status,display_name,preferred_locale,timezone,created_at::text`,[input.displayName?.trim().slice(0,160)||null])).rows[0];await client.query(`INSERT INTO accounts.identities(user_id,identity_type,normalized_value,display_value) VALUES($1,'email',$2,$3)`,[u.id,email,input.email.trim()]);await client.query(`INSERT INTO accounts.password_credentials(user_id,password_hash,password_salt) VALUES($1,$2,$3)`,[u.id,hash.toString("hex"),salt]);await client.query(`INSERT INTO accounts.audit_events(actor_user_id,subject_user_id,action,snapshot) VALUES($1,$1,'account_created',$2::jsonb)`,[u.id,JSON.stringify({identityType:"email",verificationStatus:"unverified"})]);await client.query("COMMIT");return createSession(u.id,input.userAgent,input.ipAddress);}catch(e){await client.query("ROLLBACK");if((e as {code?:string}).code==="23505")throw new Error("An account already exists for this email.");throw e;}finally{client.release();}}
export async function createSession(userId:string,userAgent?:string|null,ipAddress?:string|null){const token=randomBytes(32).toString("base64url");await query(`INSERT INTO accounts.sessions(user_id,token_hash,expires_at,user_agent,ip_address) VALUES($1,$2,now()+($3||' days')::interval,$4,$5)`,[userId,digest(token),String(sessionDays),userAgent??null,ipAddress??null]);return token;}
export async function loginAccount(emailInput:string,password:string,userAgent?:string|null,ipAddress?:string|null){const row=await queryOne<{user_id:string;password_hash:string;password_salt:string;status:string}>(`SELECT i.user_id,c.password_hash,c.password_salt,u.status FROM accounts.identities i JOIN accounts.users u ON u.id=i.user_id JOIN accounts.password_credentials c ON c.user_id=u.id WHERE i.identity_type='email' AND i.normalized_value=$1`,[normalizeEmail(emailInput)]);if(!row||row.status!=="active")return null;const actual=await passwordHash(password,row.password_salt),expected=Buffer.from(row.password_hash,"hex");if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return null;await query(`INSERT INTO accounts.audit_events(actor_user_id,subject_user_id,action) VALUES($1,$1,'login_succeeded')`,[row.user_id]);return createSession(row.user_id,userAgent,ipAddress);}
export async function currentAccount(token:string|null):Promise<AccountUser|null>{if(!token)return null;const row=await queryOne<any>(`SELECT u.id,u.status,u.display_name,u.preferred_locale,u.timezone,u.created_at::text,i.display_value email,i.verification_status FROM accounts.sessions s JOIN accounts.users u ON u.id=s.user_id JOIN accounts.identities i ON i.user_id=u.id AND i.identity_type='email' WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND u.status='active'`,[digest(token)]);if(!row)return null;await query(`UPDATE accounts.sessions SET last_used_at=now() WHERE token_hash=$1`,[digest(token)]);return{id:row.id,status:row.status,displayName:row.display_name,preferredLocale:row.preferred_locale,timezone:row.timezone,email:row.email,emailVerificationStatus:row.verification_status,createdAt:row.created_at};}
export async function logoutAccount(token:string|null){if(token)await query(`UPDATE accounts.sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL`,[digest(token)]);}
function maskEmail(value:string){const [name,domain]=value.split("@");return `${name.slice(0,2)}***@${domain}`;}
export async function issueChallenge(input:{type:"verify_identity"|"recover_account";userId?:string;email?:string;origin:string}){
  const identity=input.userId?await queryOne<any>(`SELECT id,user_id,display_value,verification_status FROM accounts.identities WHERE user_id=$1 AND identity_type='email'`,[input.userId]):await queryOne<any>(`SELECT id,user_id,display_value,verification_status FROM accounts.identities WHERE identity_type='email' AND normalized_value=$1`,[normalizeEmail(input.email??"")]);
  if(!identity)return {accepted:true,developmentUrl:null};if(input.type==="verify_identity"&&identity.verification_status==="verified")return {accepted:true,developmentUrl:null};
  const recent=await queryOne<{count:number}>(`SELECT count(*)::int count FROM accounts.challenges WHERE identity_id=$1 AND challenge_type=$2 AND created_at>now()-interval '1 hour'`,[identity.id,input.type]);if((recent?.count??0)>=3)throw new Error("Please wait before requesting another link.");
  const secret=randomBytes(32).toString("base64url");const row=await queryOne<{id:string}>(`INSERT INTO accounts.challenges(user_id,identity_id,challenge_type,secret_hash,expires_at) VALUES($1,$2,$3,$4,now()+($5||' minutes')::interval) RETURNING id`,[identity.user_id,identity.id,input.type,digest(secret),String(challengeMinutes)]);const path=input.type==="verify_identity"?"/verify-email":"/reset-password",url=`${input.origin}${path}?token=${encodeURIComponent(secret)}`;await query(`INSERT INTO accounts.delivery_outbox(identity_id,challenge_id,delivery_type,destination_masked,development_url,status) VALUES($1,$2,$3,$4,$5,'development_only')`,[identity.id,row!.id,input.type,maskEmail(identity.display_value),url]);return{accepted:true,developmentUrl:process.env.NODE_ENV==="production"?null:url};
}
async function consumeChallenge(type:"verify_identity"|"recover_account",secret:string){const row=await queryOne<any>(`SELECT id,user_id,identity_id FROM accounts.challenges WHERE challenge_type=$1 AND secret_hash=$2 AND consumed_at IS NULL AND expires_at>now()`,[type,digest(secret)]);if(!row)return null;await query(`UPDATE accounts.challenges SET consumed_at=now() WHERE id=$1 AND consumed_at IS NULL`,[row.id]);return row;}
export async function verifyEmail(secret:string){const item=await consumeChallenge("verify_identity",secret);if(!item)return false;await query(`UPDATE accounts.identities SET verification_status='verified',verified_at=now() WHERE id=$1`,[item.identity_id]);await query(`INSERT INTO accounts.audit_events(actor_user_id,subject_user_id,action,snapshot) VALUES($1,$1,'email_verified','{"verificationStatus":"verified"}'::jsonb)`,[item.user_id]);await ensureIntroductoryCredits(item.user_id);return true;}
export async function resetPassword(secret:string,password:string){if(password.length<12)throw new Error("Password must contain at least 12 characters.");const item=await consumeChallenge("recover_account",secret);if(!item)return false;const salt=randomBytes(16).toString("hex"),value=await passwordHash(password,salt);const client=await (await import("./db")).pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE accounts.password_credentials SET password_hash=$2,password_salt=$3,changed_at=now() WHERE user_id=$1`,[item.user_id,value.toString("hex"),salt]);await client.query(`UPDATE accounts.sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL`,[item.user_id]);await client.query(`INSERT INTO accounts.audit_events(actor_user_id,subject_user_id,action) VALUES($1,$1,'password_reset')`,[item.user_id]);await client.query("COMMIT");return true;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
