import {randomBytes} from "node:crypto";import{pool,query}from"./db";
const orderNumber=()=>`DEN-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${randomBytes(4).toString("hex").toUpperCase()}`;
export async function createPricedOrder(input:{userId:string;productKey:string;marketKey?:string;locale:string;salesChannel?:"web"|"assisted"|"api"|"contract";idempotencyKey:string}){
 const client=await pool.connect();try{await client.query("BEGIN");const existing=(await client.query(`SELECT id,order_number,status,total_minor,charged_currency FROM commerce.orders WHERE idempotency_key=$1`,[input.idempotencyKey])).rows[0];if(existing){await client.query("COMMIT");return existing;}
 const market=input.marketKey??"NG",channel=input.salesChannel??"web";const row=(await client.query(`SELECT p.product_key,p.fulfilment_type,COALESCE(t.message,p.name_key) description,pr.id price_id,pr.amount_minor,pr.currency,pr.tax_behavior,pr.valid_from,pr.valid_to,m.default_currency
 FROM commerce.products p JOIN commerce.market_products mp ON mp.product_key=p.product_key AND mp.market_key=$2 AND mp.status='active' JOIN commerce.markets m ON m.market_key=mp.market_key AND m.status='active'
 LEFT JOIN commerce.translation_messages t ON t.message_key=p.name_key AND t.locale=$3 AND t.status='active'
 JOIN LATERAL(SELECT * FROM commerce.prices WHERE product_key=p.product_key AND market_key=$2 AND sales_channel=$4 AND status='active' AND valid_from<=now() AND(valid_to IS NULL OR valid_to>now()) ORDER BY valid_from DESC LIMIT 1)pr ON true
 WHERE p.product_key=$1 AND p.status='active'`,[input.productKey,market,input.locale,channel])).rows[0];if(!row)throw new Error("This product has no approved active price.");
 const number=orderNumber();const order=(await client.query(`INSERT INTO commerce.orders(order_number,owner_user_id,market_key,locale,status,display_currency,charged_currency,settlement_currency,accounting_currency,subtotal_minor,total_minor,idempotency_key) VALUES($1,$2,$3,$4,'awaiting_payment',$5,$5,$6,$6,$7,$7,$8) RETURNING id,order_number,status,total_minor,charged_currency`,[number,input.userId,market,input.locale,row.currency,row.default_currency,row.amount_minor,input.idempotencyKey])).rows[0];
 const snapshot={priceId:row.price_id,productKey:row.product_key,amountMinor:Number(row.amount_minor),currency:row.currency,taxBehavior:row.tax_behavior,salesChannel:channel,validFrom:row.valid_from,validTo:row.valid_to};
 const line=(await client.query(`INSERT INTO commerce.order_lines(order_id,line_type,product_key,price_id,description_snapshot,quantity,currency,unit_amount_minor,line_total_minor,price_snapshot) VALUES($1,'product',$2,$3,$4,1,$5,$6,$6,$7::jsonb) RETURNING id`,[order.id,row.product_key,row.price_id,row.description,row.currency,row.amount_minor,JSON.stringify(snapshot)])).rows[0];
 await client.query(`INSERT INTO commerce.fulfilments(order_line_id) VALUES($1)`,[line.id]);await client.query(`INSERT INTO commerce.order_events(order_id,actor_user_id,event_type,snapshot) VALUES($1,$2,'order_created',$3::jsonb)`,[order.id,input.userId,JSON.stringify({orderNumber:number,status:"awaiting_payment",price:snapshot})]);await client.query("COMMIT");return order;
 }catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function ordersForUser(userId:string){return query(`SELECT id,order_number AS "orderNumber",status,total_minor AS "totalMinor",charged_currency AS currency,created_at::text AS "createdAt" FROM commerce.orders WHERE owner_user_id=$1 ORDER BY created_at DESC`,[userId]);}
