import { createHash } from "crypto";
import { queryOne } from "./db";
import { renderTopNav, TOP_NAV_CSS } from "./nav";

export interface EvidenceReport { id:string;reportNumber:string;plotId:string;checkRunId:string;reportVersion:string;locale:string;snapshot:Record<string,unknown>;contentHash:string;generatedAt:string }
interface ReportRow { id:string;report_number:string;plot_id:string;check_run_id:string;report_version:string;locale:string;snapshot:Record<string,unknown>;content_hash:string;generated_at:string }
const mapReport=(r:ReportRow):EvidenceReport=>({id:r.id,reportNumber:r.report_number,plotId:r.plot_id,checkRunId:r.check_run_id,reportVersion:r.report_version,locale:r.locale,snapshot:r.snapshot,contentHash:r.content_hash,generatedAt:r.generated_at});
const esc=(v:unknown)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");

export async function createEvidenceReport(plotId:string,ownerUserId?:string|null):Promise<EvidenceReport|null>{
  const source=await queryOne<{plot_id:string;check_run_id:string;snapshot:Record<string,unknown>}>(`SELECT p.id plot_id,c.id check_run_id,jsonb_build_object('schemaVersion','1.0','disclaimer','Automated land-risk screening, not proof of title or legal certification.','plot',jsonb_build_object('id',p.id,'status',p.status,'method',p.method,'crs',p.crs,'computedAreaSqm',p.computed_area_sqm,'printedAreaSqm',p.printed_area_sqm,'createdAt',p.created_at,'geometry',ST_AsGeoJSON(p.geometry)::jsonb),'check',jsonb_build_object('id',c.id,'trigger',c.trigger,'parseMethod',c.parse_method,'confidence',c.confidence,'plotAreaSqm',c.plot_area_sqm,'ranAt',c.ran_at,'overlaps',c.overlaps,'zoningAlerts',c.zoning_alerts),'consultedSources',c.consulted_sources,'coverageStatement','A clean result means only that no conflict was found in the datasets listed in this report at the recorded check time.') snapshot FROM registry.plots p JOIN LATERAL(SELECT * FROM registry.check_runs WHERE plot_id=p.id ORDER BY ran_at DESC LIMIT 1)c ON true WHERE p.id=$1`,[plotId]);
  if(!source)return null;const canonical=JSON.stringify(source.snapshot),hash=createHash("sha256").update(canonical).digest("hex");
  const existing=await queryOne<ReportRow>(`SELECT id,report_number,plot_id,check_run_id,report_version,locale,snapshot,content_hash,generated_at::text FROM registry.evidence_reports WHERE check_run_id=$1 AND report_version='1.0'`,[source.check_run_id]);if(existing)return mapReport(existing);
  const number=`DENDE-${new Date().getUTCFullYear()}-${source.check_run_id.replace(/-/g,"").slice(0,12).toUpperCase()}`;
  const row=await queryOne<ReportRow>(`INSERT INTO registry.evidence_reports(report_number,plot_id,check_run_id,snapshot,content_hash,owner_user_id) VALUES($1,$2,$3,$4::jsonb,$5,COALESCE($6,(SELECT owner_user_id FROM registry.plots WHERE id=$2))) RETURNING id,report_number,plot_id,check_run_id,report_version,locale,snapshot,content_hash,generated_at::text`,[number,source.plot_id,source.check_run_id,canonical,hash,ownerUserId??null]);return row?mapReport(row):null;
}
export async function fetchEvidenceReport(id:string):Promise<EvidenceReport|null>{const row=await queryOne<ReportRow>(`SELECT id,report_number,plot_id,check_run_id,report_version,locale,snapshot,content_hash,generated_at::text FROM registry.evidence_reports WHERE id=$1`,[id]);return row?mapReport(row):null;}

export function renderEvidenceReportHtml(report:EvidenceReport):string{
  const s=report.snapshot as any,p=s.plot??{},c=s.check??{},sources=Array.isArray(s.consultedSources)?s.consultedSources:[],overlaps=Array.isArray(c.overlaps)?c.overlaps:[],alerts=Array.isArray(c.zoningAlerts)?c.zoningAlerts:[],findings=overlaps.length+alerts.length;
  const sourceRows=sources.length?sources.map((x:any)=>`<div class="source"><b>${esc(x.name)}</b><div>${esc(x.geography)} · ${esc(x.authorityLevel)} · coverage: ${esc(x.coverageStatus)}</div></div>`).join(""):'<div class="card">No versioned source was recorded.</div>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(report.reportNumber)} — Dende</title><style>${TOP_NAV_CSS}body{margin:0;background:#f4f5f2;color:#162019;font:15px/1.5 system-ui,sans-serif}.page{max-width:900px;margin:32px auto;padding:0 20px}.report{background:#fff;border:1px solid #dfe4df;border-radius:16px;padding:32px}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #193f2b;padding-bottom:20px}.eyebrow{color:#55705f;text-transform:uppercase;letter-spacing:.1em;font-size:11px;font-weight:800}h1{margin:4px 0;font-size:30px}.number,.hash{font:12px ui-monospace,monospace}.result{margin:24px 0;padding:18px;border-radius:12px;background:${findings?'#fff4e5':'#eaf7ee'}}.result b{font-size:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{border:1px solid #e3e7e3;border-radius:10px;padding:14px}h2{font-size:17px;margin:26px 0 10px}.source{padding:10px 0;border-bottom:1px solid #e8ebe8}.disclaimer{margin-top:25px;padding:14px;background:#fff8db;border-radius:10px}.hash{word-break:break-all;color:#657067}.actions{display:flex;gap:10px;margin-bottom:14px}.actions a{background:#193f2b;color:#fff;padding:9px 13px;border-radius:8px;text-decoration:none}@media(max-width:650px){.head{display:block}.grid{grid-template-columns:1fr}.report{padding:20px}}@media print{nav,.actions{display:none}.page{margin:0;max-width:none;padding:0}.report{border:0}}</style></head><body>${renderTopNav("check")}<main class="page"><div class="actions"><a href="/reports/${esc(report.id)}/download">Download evidence JSON</a><a href="javascript:print()">Print / save as PDF</a></div><article class="report"><header class="head"><div><div class="eyebrow">Permanent evidence report</div><h1>Land-risk screening</h1><div class="number">${esc(report.reportNumber)}</div></div><div>Generated<br><b>${esc(report.generatedAt)}</b></div></header><section class="result"><div class="eyebrow">Recorded result</div><b>${findings?`${findings} finding${findings===1?'':'s'}`:'No conflict found'}</b><div>${esc(s.coverageStatement)}</div></section><div class="grid"><div class="card"><div class="eyebrow">Plot</div><b>${esc(String(p.id??'').slice(0,8))}</b><div>${Number(c.plotAreaSqm??0).toFixed(1)} m² · ${esc(p.crs)}</div></div><div class="card"><div class="eyebrow">Check</div><b>${esc(c.ranAt)}</b><div>${esc(c.trigger)} · ${esc(c.parseMethod)}</div></div></div><h2>Findings</h2><div class="card">${findings?`${overlaps.length} plot overlap(s) · ${alerts.length} zoning alert(s)`:'No overlap or zoning finding was recorded in this check snapshot.'}</div><h2>Consulted sources</h2>${sourceRows}<div class="disclaimer"><b>Important:</b> ${esc(s.disclaimer)}</div><h2>Integrity</h2><div class="hash">SHA-256 ${esc(report.contentHash)}</div></article></main></body></html>`;
}
