import {createHash,randomBytes,timingSafeEqual} from "node:crypto";import {query,queryOne} from "./db";
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
const validService=new Set(["identity_documents","professional_review","authority_search","full_due_diligence"]);
const validStatus=new Set(["submitted","triage","awaiting_documents","in_review","awaiting_authority","completed","declined","cancelled"]);
export async function createVerificationCase(input:{reportId:string;serviceType:string;requesterName?:string|null;contactReference:string;requestNote?:string|null}){if(!validService.has(input.serviceType))throw new Error("Invalid verification service type.");const report=await queryOne<{plot_id:string}>(`SELECT plot_id FROM registry.evidence_reports WHERE id=$1`,[input.reportId]);if(!report)return null;const key=randomBytes(32).toString("base64url"),number=`DVC-${new Date().getUTCFullYear()}-${randomBytes(5).toString("hex").toUpperCase()}`;const row=await queryOne<any>(`INSERT INTO registry.verification_cases(case_number,report_id,plot_id,service_type,requester_name,contact_reference,request_note,management_key_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,case_number,report_id,plot_id,service_type,status,created_at::text,updated_at::text`,[number,input.reportId,report.plot_id,input.serviceType,input.requesterName??null,input.contactReference,input.requestNote??null,hash(key)]);await query(`INSERT INTO registry.verification_case_events(case_id,event_type,actor,reason,snapshot) VALUES($1,'submitted','requester:management-key',$2,$3::jsonb)`,[row.id,input.requestNote??null,JSON.stringify({status:"submitted",serviceType:input.serviceType,reportId:input.reportId})]);return {...row,managementKey:key};}
function matches(stored:string,key:string){const a=Buffer.from(stored,"hex"),b=Buffer.from(hash(key),"hex");return a.length===b.length&&timingSafeEqual(a,b)}
export async function accessVerificationCase(id:string,key:string){const row=await queryOne<any>(`SELECT id,case_number,report_id,plot_id,service_type,status,management_key_hash,created_at::text,updated_at::text,completed_at::text FROM registry.verification_cases WHERE id=$1`,[id]);if(!row||!matches(row.management_key_hash,key))return null;delete row.management_key_hash;const events=await query(`SELECT id,event_type,actor,reason,snapshot,created_at::text FROM registry.verification_case_events WHERE case_id=$1 ORDER BY id`,[id]);const evidence=await query(`SELECT id,evidence_type,title,source_url,checksum_sha256,metadata,added_by,created_at::text FROM registry.verification_case_evidence WHERE case_id=$1 ORDER BY created_at`,[id]);return {...row,events,evidence};}
export async function listVerificationQueue(){return query(`SELECT id,case_number,report_id,plot_id,service_type,requester_name,contact_reference,request_note,status,created_at::text,updated_at::text FROM registry.verification_cases WHERE status NOT IN ('completed','declined','cancelled') ORDER BY created_at`)}
export async function setVerificationCaseStatus(id:string,status:string,reason:string,actor="operator:internal"){if(!validStatus.has(status))throw new Error("Invalid verification case status.");const row=await queryOne<any>(`UPDATE registry.verification_cases SET status=$2,updated_at=now(),completed_at=CASE WHEN $2='completed' THEN now() ELSE completed_at END WHERE id=$1 RETURNING id,case_number,status,updated_at::text`,[id,status]);if(!row)return null;await query(`INSERT INTO registry.verification_case_events(case_id,event_type,actor,reason,snapshot) VALUES($1,'status_changed',$2,$3,$4::jsonb)`,[id,actor,reason,JSON.stringify({status})]);return row;}
export async function addVerificationEvidence(id:string,input:{evidenceType:string;title:string;sourceUrl?:string|null;storageUri?:string|null;checksumSha256?:string|null;metadata?:Record<string,unknown>;actor?:string}){const row=await queryOne<any>(`INSERT INTO registry.verification_case_evidence(case_id,evidence_type,title,source_url,storage_uri,checksum_sha256,metadata,added_by) SELECT $1,$2,$3,$4,$5,$6,$7::jsonb,$8 WHERE EXISTS(SELECT 1 FROM registry.verification_cases WHERE id=$1) RETURNING id,case_id,evidence_type,title,source_url,checksum_sha256,metadata,added_by,created_at::text`,[id,input.evidenceType,input.title,input.sourceUrl??null,input.storageUri??null,input.checksumSha256??null,JSON.stringify(input.metadata??{}),input.actor??"operator:internal"]);if(row)await query(`INSERT INTO registry.verification_case_events(case_id,event_type,actor,snapshot) VALUES($1,'evidence_added',$2,$3::jsonb)`,[id,input.actor??"operator:internal",JSON.stringify({evidenceId:row.id,title:input.title})]);return row;}
