-- Up Migration

-- Cross River pilot discovery pass, 2026-08-13. These records describe what
-- the cited source establishes. No record in this migration has parcel
-- geometry, so every event remains excluded from spatial checks.

WITH docs(external_key,title,publisher,publisher_type,document_type,source_url,published_on,extraction_status,metadata) AS (
 VALUES
 ('crs-wilmar-8500ha-2025','Cross River Hands Over 8,500 Hectares to Wilmar in Historic Asset Revival Deal','Cross River State Ministry of Information','government','government_news','https://news.crossriverstate.gov.ng/cross-river-hands-over-8-500-hectares-to-wilmar-in-historic-asset-revival-deal/','2025-06-16','extracted','{"discoveryPass":"cross-river-2026-08","namedPlaces":["Biase","Akamkpa","Ibiae","Kalaro"]}'::jsonb),
 ('crs-adiabo-housing-31ha-2025','Cross River Government Hands Over 31 Hectares for Federal Women''s Housing Scheme','Cross River State Ministry of Information','government','government_news','https://news.crossriverstate.gov.ng/c-river-govt-hands-over-31-hectares-of-land-to-firm-for-fg-womens-housing-scheme/','2025-01-15','extracted','{"discoveryPass":"cross-river-2026-08","namedPlaces":["Adiabo"]}'::jsonb),
 ('crs-boki-nsadop-presco-2026','Cross River Hands Over Boki, Nsadop Palm Estates to Presco for Revamp','Cross River State Ministry of Information','government','government_news','https://news.crossriverstate.gov.ng/cross-river-hands-over-boki-nsadop-palm-estates-to-presco-for-revamp/','2026-03-24','extracted','{"discoveryPass":"cross-river-2026-08","namedPlaces":["Borum","Nsadop"]}'::jsonb),
 ('crs-bansara-spin-630ha-2026','Bansara Ogoja Rice Belt Ready for Flood Control and Irrigation Farming','Cross River State Ministry of Information','government','government_news','https://news.crossriverstate.gov.ng/bansara-ogoja-rice-belt-ready-for-flood-control-and-irrigation-farming/','2026-02-23','extracted','{"discoveryPass":"cross-river-2026-08","areaMention":"approximately 630 hectares"}'::jsonb),
 ('crs-obudu-airport-1500ha-2020','Cross River Government Reports 1,500-Hectare Obudu Airport Acquisition and Compensation','CrossRiverWatch','independent','independent_report','https://crossriverwatch.com/2020/12/gov-ayade-abandons-super-highway-procures-two-aircrafts-says-obudu-intl-airport-ready-by-2021/','2020-12-01','extracted','{"discoveryPass":"cross-river-2026-08","reportedCompensationNgn":900000000}'::jsonb),
 ('crs-superhighway-revocation-2016','Superhighway Revocation Notice and Court Challenge','CrossRiverWatch','independent','independent_report','https://crossriverwatch.com/2016/09/superhighway-rainforest-resource-center-drags-cross-river-government-federal-ministry-of-environment-others-to-court/','2016-09-01','extracted','{"discoveryPass":"cross-river-2026-08","originalNotice":"Weekend Chronicle, 22 January 2016","corridorLengthKm":260,"claimedCorridorAreaKm2":5200}'::jsonb),
 ('crs-ekorinim-harbour-village-case','Nigerian Ports Authority v Attorney-General of Cross River State and Others (2014)','LawGlobal Hub','independent','court_decision','https://www.lawglobalhub.com/nigerian-ports-authority-v-attorney-general-of-cross-river-state-ors-2014-lljr-ca/',NULL,'extracted','{"discoveryPass":"cross-river-2026-08","surveyPlan":"CR6 859","reportedDecisionYear":2014}'::jsonb),
 ('crs-northern-industrial-estate-case','Government of Cross River State v NTA and Others (2013)','Judy Legal','independent','court_decision','https://www.judy.legal/case/the-gov-of-cross-river-state-anor-v-nta-ors-appeal-2013',NULL,'extracted','{"discoveryPass":"cross-river-2026-08","reportedDecisionYear":2013}'::jsonb),
 ('crs-ikot-uduak-nitel-case','Surveyor General of Cross River State and Others v Opute Jonathan and Others (2014)','LawGlobal Hub','independent','court_decision','https://www.lawglobalhub.com/the-surveyor-general-of-cross-river-state-ors-v-mr-opute-jonathan-ors-2014-lljr-ca/',NULL,'extracted','{"discoveryPass":"cross-river-2026-08","reportedDecisionYear":2014}'::jsonb),
 ('crs-fggc-calabar-additional-land-case','Hon. Minister, Federal Ministry of Education and Others v Prince Ekpo Okang Ekpo and Others (2016)','LawGlobal Hub','independent','court_decision','https://www.lawglobalhub.com/hon-minister-federal-ministry-of-education-ors-v-prince-ekpo-okang-ekpo-ors-2016-lljr-ca/',NULL,'extracted','{"discoveryPass":"cross-river-2026-08","reportedDecisionYear":2016}'::jsonb),
 ('crs-ugep-idomi-ketabebe-case-2026','Ugep Community Sues Cross River State over Ketabebe Frontier Land Dispute','The Guardian Nigeria','independent','independent_report','https://guardian.ng/news/ugep-community-sues-cross-river-state-over-ketabebe-frontier-land-dispute/','2026-07-04','extracted','{"discoveryPass":"cross-river-2026-08","reportedAllocationRatio":"45-40-15"}'::jsonb),
 ('crs-blanket-revocation-2025','All Land Allocated Without Due Process Revoked in Cross River','CrossRiverWatch','independent','independent_report','https://crossriverwatch.com/2025/11/all-land-allocated-without-due-process-revoked-in-cross-river/','2025-11-10','extracted','{"discoveryPass":"cross-river-2026-08","scope":"allocations described as lacking due process"}'::jsonb),
 ('crs-2024-q4-budget-performance','Cross River State 2024 Q4 Budget Performance Report','Cross River State Government','government','budget','https://crossriverstate.gov.ng/download/CRS%202024%20Q4%20BPR3%20FOR%20PUBLICATION.pdf','2025-01-01','extracted','{"discoveryPass":"cross-river-2026-08","landPages":[71,86],"visuallyVerified":true}'::jsonb),
 ('crs-2026-proposed-budget','Cross River State Government 2026 Proposed Budget','Cross River State Government','government','budget','https://www.crossriverstate.gov.ng/download/Budget/2026%20PROPOSED%20BUDGET%20ONLINE.pdf','2025-12-01','extracted','{"discoveryPass":"cross-river-2026-08","landPages":[329,464],"visuallyVerified":true}'::jsonb),
 ('ng-npa-decree-properties','Nigerian Ports Authority Decree - Schedule of Vested Properties','Federal Republic of Nigeria','legal_authority','legal_instrument','https://faolex.fao.org/docs/pdf/nig61964.pdf',NULL,'discovered','{"discoveryPass":"cross-river-2026-08","crossRiverEntry":"Harbour Village, Ekorinim; 11.048 hectares; CR6 859"}'::jsonb)
)
INSERT INTO intelligence.documents(external_key,title,publisher,publisher_type,document_type,source_url,published_on,extraction_status,metadata)
SELECT external_key,title,publisher,publisher_type,document_type,source_url,published_on::date,extraction_status,metadata FROM docs
ON CONFLICT(external_key) DO NOTHING;

-- The fuller official Summit Hills report contains survey and tracing numbers
-- absent from the original four-record pilot.
UPDATE intelligence.land_events SET
  effective_on='2024-10-30',
  survey_reference='CR/C/1187; tracing CRC.2881 and CRC/2878',
  original_area_text='23 hectares released; ceding notice identifies 12.110 ha and 9.074 ha parcels',
  summary='Following consent judgment HC/314/2021, the state handed the Nkonib community an approved layout plan. The official report names survey plan CR/C/1187 and tracing numbers CRC.2881 and CRC/2878, while also reporting 12.110 ha and 9.074 ha ceded parcels.',
  updated_at=now()
WHERE external_key='crs-summit-hills-nkonib-return';

WITH events(external_key,event_type,headline,summary,effective_on,admin_level_2,locality,layout_name,plot_reference,survey_reference,court_reference,area_sqm,original_area_text,evidence_tier,confidence) AS (
 VALUES
 ('crs-wilmar-biase-8500ha-allocation','allocation','Over 8,500 hectares and plantation assets transferred to Wilmar subsidiary','The state reports an asset-sale agreement transferring over 8,500 hectares formerly managed by Enghuat Industries/Cross River Estates to Biase Plantations Limited. The article identifies Ibiae and Kalaro estates but supplies no parcel plan.','2025-06-16',NULL,'Biase and Akamkpa','Ibiae and Kalaro oil palm estates',NULL,NULL,NULL,85000000::numeric,'over 8,500 hectares',2::smallint,0.96::numeric),
 ('crs-adiabo-womens-housing-31ha','allocation','31 hectares at Adiabo handed over for women''s housing scheme','The state reports handing 31 hectares at Adiabo to Family Homes Funds for a 70-unit federal women''s housing scheme. No survey reference or boundary was published.','2025-01-15',NULL,'Adiabo',NULL,NULL,NULL,NULL,310000::numeric,'31 hectares',2::smallint,0.97::numeric),
 ('crs-boki-palm-estate-presco-handover','allocation','Boki palm estate handed over to Presco for rehabilitation','The state reports the formal handover of the Boki estate to Presco following a privatization process. The publication does not state its area or boundary.','2026-03-20','Boki','Borum','Boki Palm Estate',NULL,NULL,NULL,NULL,NULL,2::smallint,0.91::numeric),
 ('crs-nsadop-palm-estate-presco-handover','allocation','Nsadop palm estate handed over to Presco for rehabilitation','The state reports the formal handover of the Nsadop estate to Presco following a privatization process. The publication does not state its area or boundary.','2026-03-21','Boki','Nsadop','Nsadop Palm Estate',NULL,NULL,NULL,NULL,NULL,2::smallint,0.91::numeric),
 ('crs-bansara-spin-630ha-site','planning_change','Approximately 630 hectares at Bansara assessed for irrigation development','An official project report describes a technical verification visit across approximately 630 hectares proposed for flood-control and irrigation works under SPIN. This is a project-site report, not evidence of title transfer.','2026-02-23','Ogoja','Bansara','Bansara SPIN site',NULL,NULL,NULL,6300000::numeric,'approximately 630 hectares',2::smallint,0.94::numeric),
 ('crs-obudu-airport-1500ha-acquisition','acquisition','Reported 1,500-hectare acquisition for Obudu international airport','A contemporaneous report quotes the state as having acquired about 1,500 hectares and paid nearly NGN900 million compensation to five land-owning communities for the airport project. The acquisition instrument and survey plan were not found.','2020-12-01','Obudu','Obudu',NULL,NULL,NULL,NULL,15000000::numeric,'about 1,500 hectares',3::smallint,0.86::numeric),
 ('crs-superhighway-occupancy-revocation-2016','revocation','Rights of occupancy revoked along proposed 260 km superhighway corridor','Reports reproduce a 22 January 2016 Weekend Chronicle notice revoking occupancy along the proposed Esighi-to-Bekwarra superhighway. The reported notice described a 200 m offset on each side plus a further 10 km span, excluding reserves and public institutions; 5,200 km2 is a civil-society computation, not surveyed parcel area.','2016-01-22',NULL,'Esighi to Bekwarra','Cross River Superhighway corridor',NULL,NULL,NULL,5200000000::numeric,'reported/contested computation of 5,200 km2',3::smallint,0.84::numeric),
 ('crs-ekorinim-harbour-village-revocation-dispute','court_decision','11.048-hectare Harbour Village revocation and revalidation disputed in court','The reported Court of Appeal matter concerns Harbour Village at Ekorinim, originally vested in the Nigerian Ports Authority and later subject to a 26 November 2007 revocation/revalidation. The source identifies survey plan CR6 859. The judgment text must be reviewed before encoding the final legal effect. ',NULL,'Calabar Municipal','Ekorinim','Harbour Village',NULL,'CR6 859','NPA v Attorney-General of Cross River State & Ors (2014)',110480::numeric,'approximately 11.048 hectares',3::smallint,0.90::numeric),
 ('crs-northern-industrial-estate-7ha-case','court_decision','7.139-hectare federal property dispute at Northern Industrial Estate','The reported appeal concerns federal-agency land along Murtala Mohammed Highway, Block N, Northern Industrial Estate, Ikot Ansa, and challenges state revocation and sale. The final legal effect requires judgment-level review. ',NULL,'Calabar Municipal','Ikot Ansa','Northern Industrial Estate','Block N',NULL,'Government of Cross River State v NTA & Ors (2013)',71390::numeric,'7.139 hectares',3::smallint,0.88::numeric),
 ('crs-ikot-uduak-nitel-10ha-case','court_decision','10.443-hectare Ikot Uduak acquisition and NITEL quarters dispute','The reported appeal traces a 1973 state acquisition of 10.443 hectares for P&T/NITEL, of which 2.639 hectares was developed and 7.804 hectares remained undeveloped. It records a later dispute involving retired NITEL staff.','1973-01-01','Calabar Municipal','Ikot Uduak','NITEL Senior Staff Quarters',NULL,NULL,'Surveyor General of Cross River State & Ors v Opute Jonathan & Ors (2014)',104430::numeric,'10.443 hectares total; 2.639 developed; 7.804 undeveloped',3::smallint,0.89::numeric),
 ('crs-fggc-calabar-additional-11ha-case','court_decision','11.884-hectare additional FGGC Calabar land became subject of return/compensation dispute','The reported appeal says the state surveyed 11.884 hectares of Adohose family land in 1982 for additional FGGC land, advised in 2006 that it was no longer needed, and later disputed whether compensation had been paid. The record is a dispute, not proof of current ownership.','1982-01-01','Calabar Municipal','Calabar','Federal Government Girls College additional land',NULL,NULL,'Hon Minister of Education & Ors v Ekpo & Ors (2016)',118840::numeric,'11.884 hectares additional land',3::smallint,0.88::numeric),
 ('crs-ugep-idomi-ketabebe-dispute-2026','dispute','Ugep challenges proposed Ketabebe land-sharing formula','The Guardian reports a High Court action challenging a proposed 45-40-15 allocation among Ugep, Idomi and the state at the Ketabebe frontier. This records the existence of a live dispute; it does not validate either side''s title claim.','2026-07-04','Yakurr','Ketabebe frontier',NULL,NULL,NULL,NULL,NULL,'reported 45-40-15 sharing ratio',3::smallint,0.90::numeric),
 ('crs-undue-process-allocations-revoked-2025','revocation','State reportedly revoked land allocations made without due process','A report reproducing a governor''s press release says allocations determined to have been made without due process were revoked statewide. No affected-plot schedule was found, so the record cannot identify individual titles.','2025-11-10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'all allocations described as lacking due process',3::smallint,0.87::numeric),
 ('crs-50000ha-agric-land-programme','acquisition','Budget pipeline covers acquisition, compensation and survey of 50,000 hectares','The 2024 performance report and 2026 proposed budget contain separate lines for acquisition/land rent, crop enumeration and compensation, survey, and ESIA for a 50,000-hectare public-private agriculture programme. It is state-wide programme evidence, not a parcel boundary.','2024-01-01',NULL,NULL,NULL,NULL,NULL,NULL,500000000::numeric,'50,000 hectares, state wide',2::smallint,0.98::numeric),
 ('crs-2024-acquired-land-survey-programme','survey_approval','2024 report records acquired-land survey and boundary-survey programmes','The Q4 budget performance report records Ministry of Lands projects for acquisition and compensation, survey/percolation of government-acquired land, survey/documentation of state facilities and a boundary survey programme. It does not list affected parcels.','2024-12-31',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2::smallint,0.98::numeric)
)
INSERT INTO intelligence.land_events(external_key,event_type,headline,summary,effective_on,country_code,admin_level_1,admin_level_2,locality,layout_name,plot_reference,survey_reference,court_reference,area_sqm,original_area_text,geometry_status,extraction_confidence,evidence_tier,review_status,search_status,check_status)
SELECT external_key,event_type,headline,summary,effective_on::date,'NG','Cross River',admin_level_2,locality,layout_name,plot_reference,survey_reference,court_reference,area_sqm,original_area_text,'unavailable',confidence,evidence_tier,'accepted','searchable','excluded'
FROM events ON CONFLICT(external_key) DO NOTHING;

INSERT INTO intelligence.event_evidence(event_id,document_id,evidence_role,locator,supporting_excerpt)
SELECT e.id,d.id,'supports',x.locator,x.excerpt
FROM (VALUES
 ('crs-wilmar-biase-8500ha-allocation','crs-wilmar-8500ha-2025','article','Official report states transfer of over 8,500 hectares and assets.'),
 ('crs-adiabo-womens-housing-31ha','crs-adiabo-housing-31ha-2025','article','Official report states 31 hectares at Adiabo were handed over.'),
 ('crs-boki-palm-estate-presco-handover','crs-boki-nsadop-presco-2026','article','Official report records handover of Boki estate.'),
 ('crs-nsadop-palm-estate-presco-handover','crs-boki-nsadop-presco-2026','article','Official report records handover of Nsadop estate.'),
 ('crs-bansara-spin-630ha-site','crs-bansara-spin-630ha-2026','article','Official report describes approximately 630 hectares visited.'),
 ('crs-obudu-airport-1500ha-acquisition','crs-obudu-airport-1500ha-2020','quoted state statement','Report quotes acquisition of about 1,500 hectares and compensation to five communities.'),
 ('crs-superhighway-occupancy-revocation-2016','crs-superhighway-revocation-2016','reproduced notice and claim','Report reproduces the corridor description and records the court challenge.'),
 ('crs-ekorinim-harbour-village-revocation-dispute','crs-ekorinim-harbour-village-case','reported judgment','Reported judgment identifies Harbour Village, area and CR6 859.'),
 ('crs-ekorinim-harbour-village-revocation-dispute','ng-npa-decree-properties','property schedule','Federal legal instrument schedule lists Harbour Village, 11.048 hectares and CR6 859.'),
 ('crs-northern-industrial-estate-7ha-case','crs-northern-industrial-estate-case','reported judgment','Reported appeal identifies Block N and 7.139 hectares.'),
 ('crs-ikot-uduak-nitel-10ha-case','crs-ikot-uduak-nitel-case','reported judgment','Reported appeal provides acquisition and developed/undeveloped areas.'),
 ('crs-fggc-calabar-additional-11ha-case','crs-fggc-calabar-additional-land-case','reported judgment','Reported appeal describes the 11.884-hectare additional acquisition dispute.'),
 ('crs-ugep-idomi-ketabebe-dispute-2026','crs-ugep-idomi-ketabebe-case-2026','news report','Report records the filed action and challenged 45-40-15 formula.'),
 ('crs-undue-process-allocations-revoked-2025','crs-blanket-revocation-2025','reported press release','Report states a statewide directive but includes no plot schedule.'),
 ('crs-50000ha-agric-land-programme','crs-2024-q4-budget-performance','page 71','Budget table lists acquisition, compensation, survey and ESIA for 50,000 hectares.'),
 ('crs-50000ha-agric-land-programme','crs-2026-proposed-budget','page 329','Proposed budget repeats acquisition, compensation, survey and ESIA lines.'),
 ('crs-2024-acquired-land-survey-programme','crs-2024-q4-budget-performance','page 86','Visually verified Ministry of Lands and Surveyor-General project rows.')
) x(event_key,document_key,locator,excerpt)
JOIN intelligence.land_events e ON e.external_key=x.event_key
JOIN intelligence.documents d ON d.external_key=x.document_key
ON CONFLICT DO NOTHING;

INSERT INTO intelligence.document_assets(document_id,external_key,discovered_from_url,file_url,filename,format_family,file_extension,media_type,byte_size,checksum_sha256,acquisition_status,extraction_status,page_count,text_layer_status,acquired_at,metadata)
SELECT d.id,x.asset_key,x.url,x.url,x.filename,'pdf','pdf','application/pdf',x.byte_size,x.checksum,x.acquisition_status,x.extraction_status,x.page_count,x.text_layer_status,CASE WHEN x.acquisition_status='downloaded' THEN now() END,x.metadata
FROM (VALUES
 ('crs-2024-q4-budget-performance-pdf','crs-2024-q4-budget-performance','https://crossriverstate.gov.ng/download/CRS%202024%20Q4%20BPR3%20FOR%20PUBLICATION.pdf','CRS 2024 Q4 BPR3 FOR PUBLICATION.pdf',1394604::bigint,'f89e4cfe899d7314a2c318ceb4b1c3a177ea71048f6cfea5006a6d7c19ef0b74','downloaded','text_extracted',106,'present','{"landPages":[71,86],"downloadedDuring":"cross-river-2026-08"}'::jsonb),
 ('crs-2026-proposed-budget-pdf','crs-2026-proposed-budget','https://www.crossriverstate.gov.ng/download/Budget/2026%20PROPOSED%20BUDGET%20ONLINE.pdf','2026 PROPOSED BUDGET ONLINE.pdf',7394527::bigint,'de410b34e7ea94b6cf0f0d51ae6d70cc7a1e208ff0ba85ed55b78305dd5c5529','downloaded','text_extracted',616,'present','{"landPages":[329,464],"downloadedDuring":"cross-river-2026-08"}'::jsonb),
 ('ng-npa-decree-properties-pdf','ng-npa-decree-properties','https://faolex.fao.org/docs/pdf/nig61964.pdf','nig61964.pdf',NULL,NULL,'discovered','pending',NULL,'unknown','{"numericTargets":["Harbour Village","CR6 859","11.048 hectares"]}'::jsonb),
 ('crs-superhighway-fact-sheet-pdf',NULL,'https://www.iccaconsortium.org/wp-content/uploads/2016/04/event-2016-nigeria-Super-Highway-Fact-Sheet-18March.pdf','Cross River Super Highway Fact Sheet.pdf',NULL,NULL,'discovered','pending',NULL,'unknown','{"numericTargets":["260 km","20 km corridor","5200 sq km"]}'::jsonb)
) x(asset_key,document_key,url,filename,byte_size,checksum,acquisition_status,extraction_status,page_count,text_layer_status,metadata)
LEFT JOIN intelligence.documents d ON d.external_key=x.document_key
ON CONFLICT(external_key) DO NOTHING;

INSERT INTO intelligence.review_events(land_event_id,event_type,actor,reason,snapshot)
SELECT e.id,'accepted','system:cross-river-discovery-pass','Reviewed source-level claim; retained geometry exclusion pending parcel evidence',
 jsonb_build_object('reviewStatus',e.review_status,'searchStatus',e.search_status,'checkStatus',e.check_status,'evidenceTier',e.evidence_tier,'geometryStatus',e.geometry_status)
FROM intelligence.land_events e
WHERE (e.external_key IN (
 'crs-wilmar-biase-8500ha-allocation','crs-adiabo-womens-housing-31ha','crs-boki-palm-estate-presco-handover','crs-nsadop-palm-estate-presco-handover','crs-bansara-spin-630ha-site','crs-obudu-airport-1500ha-acquisition','crs-superhighway-occupancy-revocation-2016','crs-ekorinim-harbour-village-revocation-dispute','crs-northern-industrial-estate-7ha-case','crs-ikot-uduak-nitel-10ha-case','crs-fggc-calabar-additional-11ha-case','crs-ugep-idomi-ketabebe-dispute-2026','crs-undue-process-allocations-revoked-2025','crs-50000ha-agric-land-programme','crs-2024-acquired-land-survey-programme'))
AND NOT EXISTS(SELECT 1 FROM intelligence.review_events r WHERE r.land_event_id=e.id);

-- Down Migration
-- Evidence records are append-only by design. This production-like discovery
-- migration intentionally has no destructive rollback.
