-- Up Migration

ALTER TABLE provenance.spatial_asset_inventory
  ADD COLUMN risk_priority smallint NOT NULL DEFAULT 3 CHECK (risk_priority BETWEEN 1 AND 5),
  ADD COLUMN risk_reason text;

WITH assets(external_key,asset_name,alternate_names,asset_class,authority_name,admin_level_2,locality,legal_status,instrument_reference,survey_reference,stated_area_sqm,source_url,acquisition_status,missing_material,next_action,evidence_notes,risk_priority,risk_reason) AS (VALUES
 ('crs-asset-tinapa','Tinapa Business and Leisure Resort / Free Zone',ARRAY['Tinapa Resort','Tinapa Business Resort','Tinapa Free Zone and Resort'],'government_estate','Cross River State Government / Tinapa Business Resort Limited','Odukpani','Adiabo / Ekabo','acquired',NULL,NULL,2650000::numeric,'https://news.crossriverstate.gov.ng/cross-river-reclaims-tinapa-management-from-amcon/','source_found','Acquisition plan, free-zone designation plan, perimeter survey and current title/receivership boundary','Acquire settlement/acquisition schedules from CRSG/AMCON and designation plan from NEPZA; reconcile the reported 265-hectare footprint before geometry extraction','State confirms repossession from AMCON. The 265-hectare figure is reported by AMCON-related public material and remains unverified pending plans.',1,'Large, partly underused government compound beside expanding peri-urban land markets; high encroachment and fraudulent-sale exposure.'),
 ('crs-asset-marina-resort','Marina Resort Calabar',ARRAY['Calabar Marina Resort','Marina Resort'],'government_estate','Cross River State Tourism Bureau','Calabar South','Calabar waterfront','acquired',NULL,NULL,NULL,'https://pppportal.ipb.cr.gov.ng/','source_found','Title/acquisition instrument, cadastral plan, waterfront limits and jetty/water boundary','Request asset schedule and perimeter survey from Tourism Bureau/Lands; inspect PPP, EIA and jetty files for plans','Current state PPP pipeline and budgets identify Marina Resort as a government tourism asset under implementation.',1,'Waterfront asset with valuable adjoining urban land, irregular shoreline geometry and significant encroachment risk.'),
 ('crs-asset-summit-hills','Summit Hills Development',ARRAY['Summit Hills Estate','Summit Hills'],'planning_zone','Cross River State Government / Summit Hills Estate Limited','Calabar Municipal','Ikot Ansa / Nkonib', 'acquired','HC/314/2021 settlement and 2024 public notice','CR/C 1187',3670000::numeric,'https://news.crossriverstate.gov.ng/crsg-hands-over-23-hectares-of-land-at-summit-hills-to-nkonib-community/','file_found','Complete CR/C 1187 survey plan, original acquisition perimeter, ceded parcel rings and current residual-government-land schedule','Acquire deposited plan CR/C 1187 and settlement schedules; reconstruct original, ceded and residual polygons separately','Official notice identifies two ceded portions of 12.110 and 9.074 hectares on CR/C 1187. The wider 367-hectare figure is secondary and must be verified.',1,'Recent boundary change and return of community land create high risk of confusing ceded parcels with residual government holdings.'),
 ('crs-asset-cicc','Calabar International Convention Centre compound',ARRAY['CICC'],'public_institution','Cross River State Government','Calabar Municipal','Summit Hills','acquired',NULL,NULL,NULL,'https://ipb.cr.gov.ng/investment-opportunities-in-infrastructure/','source_found','Compound/site plan and relationship to the wider Summit Hills acquisition','Obtain CICC site/layout plan and intersect only after the Summit Hills parent boundary is validated','Official investment material identifies CICC as a state infrastructure project connected to Tinapa.',2,'High-value public facility inside a larger changing development footprint.'),
 ('crs-asset-summit-hills-monorail-row','Summit Hills–Tinapa monorail right-of-way',ARRAY['Calabar Monorail','CICC-Tinapa Monorail'],'transport_right_of_way','Cross River State Government','Calabar Municipal','Summit Hills to Tinapa','acquired',NULL,NULL,NULL,'https://ipb.cr.gov.ng/investment-opportunities-in-infrastructure/','source_found','As-built alignment, station compounds, easement/ROW width and acquisition schedule','Acquire engineering/as-built drawings and ROW schedule; validate endpoints against CICC and Tinapa plans','Official investment page identifies a monorail connection between CICC and Tinapa.',1,'Linear corridor is easily crossed by submitted plots and must not be approximated from a visual route.'),
 ('crs-asset-calabar-free-trade-zone','Calabar Free Trade Zone',ARRAY['CFTZ','Calabar Export Processing Zone'],'industrial_area','Nigeria Export Processing Zones Authority','Calabar Municipal','Esuk Utan / Calabar Port area','gazetted','Federal designation, 1992',NULL,NULL,'https://nepza.gov.ng/free-zones/operational-zones/','source_found','Designation instrument, original perimeter plan and 98.024-hectare extension survey','Request designation and extension polygons from NEPZA; locate gazette and survey documents in federal records','NEPZA lists CFTZ as a federal operational zone. A reported 2002 extension of 98.024 hectares requires primary confirmation.',1,'Active industrial/free-zone land has high transaction value and severe consequences for overlapping private sales.'),
 ('crs-asset-obudu-mountain-resort','Obudu Mountain Resort',ARRAY['Obudu Cattle Ranch','Obudu Plateau Resort'],'government_estate','Cross River State Government','Obanliku','Obudu Plateau','acquired',NULL,NULL,NULL,'https://news.crossriverstate.gov.ng/gov-otu-injects-n18bn-into-cross-river-tourism/','source_found','Government asset/title schedule, perimeter survey, resort lease/concession boundaries and protected landscape constraints','Acquire Lands/Tourism asset plan and distinguish resort property from surrounding community and conservation land','State identifies Obudu Mountain Resort among tourism assets receiving rehabilitation funding.',1,'Large remote government estate with adjoining community land and tourism-development pressure.'),
 ('crs-asset-kwa-falls','Kwa Falls tourism and conservation compound',ARRAY['Kwa Waterfalls','Kwa Falls'],'conservation_area','Cross River State Government','Akamkpa','Kwa Falls','acquired',NULL,NULL,NULL,'https://news.crossriverstate.gov.ng/gov-otu-injects-n18bn-into-cross-river-tourism/','source_found','Tourism asset perimeter, conservation/buffer designation, access ROW and watercourse limits','Acquire Tourism/Forestry/Lands plans and verify whether multiple legal layers overlap','State identifies Kwa Falls as a tourism asset; exact ownership and conservation perimeter are not published.',1,'Tourism, forest and watercourse interests may overlap, creating multiple restrictions around adjoining land.'),
 ('crs-asset-uj-esuene-stadium','U. J. Esuene Stadium compound',ARRAY['Calabar Stadium','U.J. Esuene Stadium'],'public_institution','Cross River State Government','Calabar Municipal','Calabar', 'acquired',NULL,NULL,NULL,'https://www.crossriverstate.gov.ng/','not_started','Title/acquisition instrument and compound survey','Search Sports Commission, budget, procurement and Lands records for site/perimeter plan','Obvious state civic/sports holding added under the urban government asset completeness rule.',2,'Dense urban location makes perimeter confusion and edge encroachment commercially relevant.'),
 ('crs-asset-cultural-centre-calabar','Cultural Centre Calabar compound',ARRAY['Cross River Cultural Centre'],'public_institution','Cross River State Government','Calabar Municipal','Calabar','acquired',NULL,NULL,NULL,'https://www.crossriverstate.gov.ng/','not_started','Title/acquisition instrument and compound survey','Search Culture/Tourism, procurement and Lands records for site plan','State cultural/civic property added under the urban government asset completeness rule.',2,'High-value central urban government land with redevelopment and informal-use exposure.')
)
INSERT INTO provenance.spatial_asset_inventory(
 campaign_id,external_key,asset_name,alternate_names,asset_class,authority_name,country_code,admin_level_1,admin_level_2,locality,
 legal_status,instrument_reference,survey_reference,stated_area_sqm,source_url,acquisition_status,missing_material,next_action,evidence_notes,risk_priority,risk_reason
)
SELECT c.id,a.external_key,a.asset_name,a.alternate_names,a.asset_class,a.authority_name,'NG','Cross River',a.admin_level_2,a.locality,
 a.legal_status,a.instrument_reference,a.survey_reference,a.stated_area_sqm,a.source_url,a.acquisition_status,a.missing_material,a.next_action,a.evidence_notes,a.risk_priority,a.risk_reason
FROM assets a JOIN provenance.spatial_acquisition_campaigns c ON c.external_key='ng-cross-river-spatial-rerun-v1'
ON CONFLICT(external_key) DO NOTHING;

UPDATE provenance.spatial_acquisition_campaigns
SET notes='Validation started for parks. Urban government asset gap corrected: Tinapa, Marina, Summit Hills, CICC, monorail ROW, CFTZ, Obudu Resort, Kwa Falls and central civic compounds added with risk priority.'
WHERE external_key='ng-cross-river-spatial-rerun-v1';

-- Down Migration
DELETE FROM provenance.spatial_asset_inventory WHERE external_key IN (
 'crs-asset-tinapa','crs-asset-marina-resort','crs-asset-summit-hills','crs-asset-cicc',
 'crs-asset-summit-hills-monorail-row','crs-asset-calabar-free-trade-zone',
 'crs-asset-obudu-mountain-resort','crs-asset-kwa-falls','crs-asset-uj-esuene-stadium',
 'crs-asset-cultural-centre-calabar');
ALTER TABLE provenance.spatial_asset_inventory DROP COLUMN risk_reason,DROP COLUMN risk_priority;
