-- Up Migration

ALTER TABLE provenance.spatial_asset_inventory
  ADD COLUMN processing_status text NOT NULL DEFAULT 'queued'
    CHECK (processing_status IN ('queued','claimed','researching','geometry_found','validating','complete','blocked')),
  ADD COLUMN claimed_at timestamptz,
  ADD COLUMN completed_at timestamptz;
CREATE INDEX spatial_asset_processing_queue_idx ON provenance.spatial_asset_inventory(campaign_id,processing_status,risk_priority,created_at);

WITH assets(external_key,asset_name,alternate_names,asset_class,authority_name,admin_level_2,locality,legal_status,stated_area_sqm,source_url,acquisition_status,evidence_notes,risk_priority,risk_reason) AS (VALUES
 ('crs-asset-afi-mountain-wildlife-sanctuary','Afi Mountain Wildlife Sanctuary',ARRAY['Afi Mountain Nature Reserve','Afi Mountain Sanctuary'],'conservation_area','Cross River State Forestry Commission / conservation partners','Boki','Afi Mountain','declared',NULL,'https://www.crossriverstate.gov.ng/download/Bureau%20of%20Statistics/SUSTAINABLE%20FINAL%20PRINT-1.pdf','source_found','Official state publication lists Afi Mountain Nature Reserve as a tourism/conservation asset.',1,'Protected land with known agricultural and settlement pressure.'),
 ('crs-asset-drill-ranch','Drill Rehabilitation and Breeding Centre',ARRAY['Drill Ranch','Pandrillus Drill Ranch'],'conservation_area','Cross River State tourism/conservation authorities and operator','Boki',NULL,'reported',NULL,'https://www.crossriverstate.gov.ng/download/Bureau%20of%20Statistics/SUSTAINABLE%20FINAL%20PRINT-1.pdf','source_found','Official state publication lists the centre in Boki.',2,'Conservation compound and surrounding forest interests require separation.'),
 ('crs-asset-agbokim-waterfalls','Agbokim Waterfalls tourism/conservation area',ARRAY['Agbokim Falls'],'conservation_area','Cross River State Ministry of Tourism, Arts and Culture','Etung','Agbokim','reported',NULL,'https://news.crossriverstate.gov.ng/criver-tourism-ministry-embarks-on-familiarization-tour-of-agbokim-waterfalls-alok-ikom-monoliths/','source_found','Official ministry identifies Agbokim as a key heritage/tourism site.',1,'Watercourse, access and tourism land are vulnerable to informal subdivision.'),
 ('crs-asset-alok-monoiths','Alok Ikom Monoliths heritage area',ARRAY['Alok Monoliths','Ikom Monoliths'],'conservation_area','Cross River State Ministry of Tourism, Arts and Culture / heritage authorities','Ikom','Alok','reported',NULL,'https://news.crossriverstate.gov.ng/criver-tourism-ministry-embarks-on-familiarization-tour-of-agbokim-waterfalls-alok-ikom-monoliths/','source_found','Official ministry identifies the monoliths as a key heritage site.',1,'Heritage objects and their setting need a protected compound/buffer inventory.'),
 ('crs-asset-mary-slessor-okoyong','Mary Slessor residence and tomb heritage compound',ARRAY['Mary Slessor House','Mary Slessor Tomb'],'conservation_area','Cross River State tourism/heritage authorities','Odukpani','Okoyong','reported',NULL,'https://www.crossriverstate.gov.ng/download/Bureau%20of%20Statistics/SUSTAINABLE%20FINAL%20PRINT-1.pdf','source_found','Official state publication lists the residence and tomb among state tourism sites.',2,'Historic compound requires ownership and protected-setting verification.'),
 ('crs-asset-boki-oil-palm-estate','Boki Oil Palm Estate',ARRAY['Boki Palm Estate'],'agricultural_scheme','Cross River State Government / Presco PLC','Boki',NULL,'acquired',NULL,'https://news.crossriverstate.gov.ng/cross-river-govt-initiates-technical-tender-to-privatize-4-state-owned-industrial-assets/','source_found','State identifies this as a solely state-owned asset; later handed to Presco for revival.',1,'Large estate boundary and host-community edges create significant land-sale risk.'),
 ('crs-asset-nsadop-oil-palm-estate','Nsadop Oil Palm Estate',ARRAY['Nsadop Palm Estate'],'agricultural_scheme','Cross River State Government / Presco PLC','Boki','Nsadop','acquired',NULL,'https://news.crossriverstate.gov.ng/cross-river-govt-initiates-technical-tender-to-privatize-4-state-owned-industrial-assets/','source_found','State identifies this as a solely state-owned asset; later handed to Presco for revival.',1,'Large estate boundary and host-community edges create significant land-sale risk.'),
 ('crs-asset-ugboro-fish-hatchery','Ugboro Fish Hatchery',ARRAY['Bekwarra Fish Hatchery'],'agricultural_scheme','Cross River State Government','Bekwarra','Ugboro','acquired',NULL,'https://news.crossriverstate.gov.ng/cross-river-govt-initiates-technical-tender-to-privatize-4-state-owned-industrial-assets/','source_found','State Privatisation Council identifies the hatchery as solely state-owned.',2,'Dormant rural government compound vulnerable to occupation.'),
 ('crs-asset-ibonda-fish-hatchery','Ibonda Fish Hatchery',ARRAY['Odukpani Fish Hatchery'],'agricultural_scheme','Cross River State Government','Odukpani','Ibonda','acquired',NULL,'https://news.crossriverstate.gov.ng/cross-river-govt-initiates-technical-tender-to-privatize-4-state-owned-industrial-assets/','source_found','State Privatisation Council identifies the hatchery as solely state-owned.',2,'Dormant rural government compound vulnerable to occupation.'),
 ('crs-asset-durafoam-ikom','Durafoam Industries Ikom',ARRAY['Durafoam Factory'],'industrial_area','Cross River State Government','Ikom','Ikom','acquired',NULL,'https://news.crossriverstate.gov.ng/cross-river-govt-initiates-technical-tender-to-privatize-4-state-owned-industrial-assets/','source_found','State Privatisation Council identifies Durafoam as solely state-owned.',1,'Moribund industrial land is a high-risk target for informal occupation or sale.'),
 ('crs-asset-crel-rubber-estates-akamkpa','Former CREL rubber estates - Akamkpa holdings',ARRAY['Enghaut rubber estates Akamkpa'],'agricultural_scheme','Cross River State Government','Akamkpa',NULL,'revoked',NULL,'https://news.crossriverstate.gov.ng/cross-river-sec-approves-recovery-deal-for-defunct-rubber-estates/','source_found','Part of approximately 22,000 hectares recovered across three LGAs under HC/162/2025; individual holding schedule is missing.',1,'Large recovered estate with litigation, revoked C of O and unidentified component boundaries.'),
 ('crs-asset-crel-rubber-estates-biase','Former CREL rubber estates - Biase holdings',ARRAY['Enghaut rubber estates Biase'],'agricultural_scheme','Cross River State Government','Biase',NULL,'revoked',NULL,'https://news.crossriverstate.gov.ng/cross-river-sec-approves-recovery-deal-for-defunct-rubber-estates/','source_found','Part of approximately 22,000 hectares recovered across three LGAs under HC/162/2025; individual holding schedule is missing.',1,'Large recovered estate with litigation, revoked C of O and unidentified component boundaries.'),
 ('crs-asset-crel-rubber-estates-yakurr','Former CREL rubber estates - Yakurr holdings',ARRAY['Enghaut rubber estates Yakurr'],'agricultural_scheme','Cross River State Government','Yakurr',NULL,'revoked',NULL,'https://news.crossriverstate.gov.ng/cross-river-sec-approves-recovery-deal-for-defunct-rubber-estates/','source_found','Part of approximately 22,000 hectares recovered across three LGAs under HC/162/2025; individual holding schedule is missing.',1,'Large recovered estate with litigation, revoked C of O and unidentified component boundaries.'),
 ('crs-asset-songhai-farms-itigidi','Songhai Farms Itigidi',ARRAY['Songhai Farm'],'agricultural_scheme','Cross River State Government','Abi','Itigidi','acquired',NULL,'https://news.crossriverstate.gov.ng/otu-honoured-as-economic-transformation-governor-of-the-year/','source_found','Official government report identifies this as a state asset being revitalized.',1,'Dormant/revived agricultural estate with likely extensive government land.'),
 ('crs-asset-ochon-starch-plant','Ochon Starch Processing Plant',ARRAY['Ochon starch plant'],'industrial_area','Cross River State Government',NULL,'Ochon','acquired',NULL,'https://news.crossriverstate.gov.ng/otu-honoured-as-economic-transformation-governor-of-the-year/','source_found','Official government report identifies the plant as an asset being resuscitated.',2,'Industrial compound and associated agricultural land require separate boundaries.'),
 ('crs-asset-odukpani-commercial-maize','Odukpani commercial maize farm land',ARRAY['2,000-acre Odukpani maize farm'],'agricultural_scheme','Cross River State Government','Odukpani',NULL,'reported',8093712.8448::numeric,'https://news.crossriverstate.gov.ng/otu-honoured-as-economic-transformation-governor-of-the-year/','source_found','Official report describes a 2,000-acre commercial maize farm; exact site and government interest require confirmation.',1,'Large newly used agricultural area may overlap customary or privately marketed land.'),
 ('crs-asset-ndok-rice-programme','Ndok state rice programme land',ARRAY['Ndok 50,000-hectare rice farm'],'agricultural_scheme','Cross River State Government','Ogoja','Ndok','reported',500000000::numeric,'https://news.crossriverstate.gov.ng/state-wide-address-and-media-parley-by-his-excellency-the-governor-senator-prince-bassey-edet-otu-to-commemorate-one-year-in-office-as-the-executive-governor-of-cross-river-state-29th-m/','source_found','Official address reports inauguration of a 50,000-hectare rice initiative at Ndok; tenure and participating parcels are not yet defined.',1,'Very large stated programme area must not be treated as a single government polygon without land schedules.'),
 ('crs-asset-efe-edem-okurikang-agric-land','Efe Edem Okurikang agricultural land-clearing phase',ARRAY['Odukpani agricultural land clearing'],'agricultural_scheme','Cross River State Government','Odukpani','Efe Edem Okurikang','reported',NULL,'https://news.crossriverstate.gov.ng/state-wide-address-and-media-parley-by-his-excellency-the-governor-senator-prince-bassey-edet-otu-to-commemorate-one-year-in-office-as-the-executive-governor-of-cross-river-state-29th-m/','source_found','Official address identifies this as first phase of a statewide 12,000-hectare land-clearing programme.',1,'Programme may combine multiple acquired or participating parcels and requires schedules.'),
 ('crs-asset-obudu-airport','Obudu International Passenger and Cargo Airport',ARRAY['Obudu International Airport'],'public_institution','Cross River State Government / Ministry of Aviation','Obanliku','Obudu','acquired',15000000::numeric,'https://news.crossriverstate.gov.ng/gov-otu-accelerates-aviation-infrastructure-as-obudu-international-airport-takes-shape/','source_found','State confirms ownership and active construction; earlier public reporting describes a 1,500-hectare acquisition.',1,'Airport acquisition, safety zones and approach surfaces have severe consequences for land buyers.'),
 ('crs-asset-bakassi-deep-seaport','Bakassi Deep Seaport project land',ARRAY['Bakassi Deep Sea Port'],'public_institution','Cross River State Government','Bakassi',NULL,'reported',NULL,'https://crossriverstate.gov.ng/download/CROSS%20RIVER%20State%20FY%202025Budget%20Publication.pdf','source_found','Official budget provides for perimeter and topographic survey.',1,'Large coastal acquisition with port, access and environmental restriction layers.'),
 ('crs-asset-ogoja-carnival-village','Ogoja Carnival Village',ARRAY['Carnival Village Ogoja'],'government_estate','Cross River State Government','Ogoja','Ogoja','reported',NULL,'https://news.crossriverstate.gov.ng/two-years-of-purposeful-leadership-and-shared-progress-a-state-broadcast-by-his-excellency-the-governor-of-cross-river-state-on-the-occasion-of-his-second-year-in-office-may-29-2025/','source_found','Official state broadcast identifies the project.',2,'New public tourism compound requires acquisition/site plan before surrounding sales are checked.'),
 ('crs-asset-ogoja-international-park','Ogoja International Park',ARRAY['International Park Ogoja'],'government_estate','Cross River State Government','Ogoja','Ogoja','reported',NULL,'https://news.crossriverstate.gov.ng/two-years-of-purposeful-leadership-and-shared-progress-a-state-broadcast-by-his-excellency-the-governor-of-cross-river-state-on-the-occasion-of-his-second-year-in-office-may-29-2025/','source_found','Official state broadcast identifies the project.',2,'New public tourism/civic compound requires site plan.'),
 ('crs-asset-unicross-calabar','University of Cross River State - Calabar campus',ARRAY['UNICROSS Calabar','CRUTECH Calabar'],'public_institution','Cross River State Government / UNICROSS','Calabar Municipal','Calabar','acquired',NULL,'https://news.crossriverstate.gov.ng/otu-constitutes-technical-committee-to-review-unicross-working-environment/','source_found','State confirms UNICROSS as state-owned; campus land schedule not yet inventoried.',2,'Large institutional campus in an urban land market.'),
 ('crs-asset-unicross-ogoja','University of Cross River State - Ogoja campus',ARRAY['UNICROSS Ogoja','CRUTECH Ogoja'],'public_institution','Cross River State Government / UNICROSS','Ogoja','Ogoja','acquired',NULL,'https://news.crossriverstate.gov.ng/otu-constitutes-technical-committee-to-review-unicross-working-environment/','source_found','Campus included as a distinct spatial holding; boundary source pending.',2,'Institutional land requires campus-specific perimeter.'),
 ('crs-asset-unicross-obubra','University of Cross River State - Obubra campus',ARRAY['UNICROSS Obubra','CRUTECH Obubra'],'public_institution','Cross River State Government / UNICROSS','Obubra','Obubra','acquired',NULL,'https://news.crossriverstate.gov.ng/otu-constitutes-technical-committee-to-review-unicross-working-environment/','source_found','Campus included as a distinct spatial holding; boundary source pending.',2,'Institutional land requires campus-specific perimeter.'),
 ('crs-asset-unicross-okuku','University of Cross River State - Okuku campus',ARRAY['UNICROSS Okuku','CRUTECH Okuku'],'public_institution','Cross River State Government / UNICROSS','Yala','Okuku','acquired',NULL,'https://news.crossriverstate.gov.ng/otu-constitutes-technical-committee-to-review-unicross-working-environment/','source_found','Campus included as a distinct spatial holding; boundary source pending.',2,'Institutional land requires campus-specific perimeter.')
)
INSERT INTO provenance.spatial_asset_inventory(
 campaign_id,external_key,asset_name,alternate_names,asset_class,authority_name,country_code,admin_level_1,admin_level_2,locality,legal_status,stated_area_sqm,source_url,acquisition_status,evidence_notes,risk_priority,risk_reason,
 missing_material,next_action,processing_status
)
SELECT c.id,a.external_key,a.asset_name,a.alternate_names,a.asset_class,a.authority_name,'NG','Cross River',a.admin_level_2,a.locality,a.legal_status,a.stated_area_sqm,a.source_url,a.acquisition_status,a.evidence_notes,a.risk_priority,a.risk_reason,
 'Authoritative title, acquisition/gazette instrument and boundary geometry','Keep queued until statewide inventory closes; then acquire and validate this asset alone in priority order.','queued'
FROM assets a JOIN provenance.spatial_acquisition_campaigns c ON c.external_key='ng-cross-river-spatial-rerun-v1'
ON CONFLICT(external_key) DO NOTHING;

UPDATE provenance.spatial_acquisition_campaigns
SET status='inventory',current_stage='government_inventory',
    notes='Asset validation paused. Statewide name/category/authority/source inventory must complete before single-asset processing begins.'
WHERE external_key='ng-cross-river-spatial-rerun-v1';

-- Down Migration
-- Inventory records are retained as research provenance.
