-- Up Migration

WITH assets(external_key,asset_name,alternate_names,asset_class,authority_name,admin_level_2,locality,legal_status,stated_area_sqm,source_url,acquisition_status,evidence_notes,risk_priority,risk_reason) AS (VALUES
 ('crs-asset-state-housing-estate-calabar','State Housing Estate, Calabar',ARRAY['State Housing Calabar'],'government_layout','Cross River State Ministry of Lands / CROSPIL','Calabar Municipal','State Housing','reported',NULL,'https://www.crossriverstate.gov.ng/download/Bureau%20of%20Statistics/formatted%20Personal%20F%26F%20FINAL%20PRINT-1.pdf','source_found','The official 2024 government-property schedule locates state residential quarters in State Housing Estate, Calabar; the estate plan and public/private parcel schedule are not published.',1,'Established urban estate containing government property and nearby private occupation requires parcel-level separation.'),
 ('crs-asset-okuku-gra-housing-estate','Okuku GRA Housing Estate project',ARRAY['Okuku world class GRA Housing Estate'],'government_layout','Cross River State Ministry of Housing','Yala','Okuku','reported',NULL,'https://www.crossriverstate.gov.ng/download/Budget/CROSS%20RIVER%20STATE%202026%20APPROVED%20BUDGET.pdf','source_found','Named in the official 2025/2026 budget; the entry does not establish completion, tenure or site extent.',1,'Planned government layout can be confused with surrounding market land before its acquisition and layout plans are public.'),
 ('crs-asset-obanliku-gra-housing-estate','Obanliku GRA Housing Estate project',ARRAY['Obanliku world class GRA Housing Estate'],'government_layout','Cross River State Ministry of Housing','Obanliku',NULL,'reported',NULL,'https://www.crossriverstate.gov.ng/download/Budget/CROSS%20RIVER%20STATE%202026%20APPROVED%20BUDGET.pdf','source_found','Named in the official 2025/2026 budget at LGA level; exact locality, completion, tenure and site extent are not stated.',1,'Unresolved government housing site must be identified before nearby plots can be assessed.'),
 ('crs-asset-ikom-gra-housing-estate','Ikom GRA Housing Estate project',ARRAY['Ikom world class GRA Housing Estate'],'government_layout','Cross River State Ministry of Housing','Ikom','Ikom','reported',NULL,'https://www.crossriverstate.gov.ng/download/Budget/CROSS%20RIVER%20STATE%202026%20APPROVED%20BUDGET.pdf','source_found','Named in the official 2025/2026 budget; the entry does not establish completion, tenure or site extent.',1,'Government layout in an active urban land market requires acquisition and approved-layout plans.'),
 ('crs-asset-odukpani-gra-housing-estate','Odukpani GRA Housing Estate project',ARRAY['Odukpani world class GRA Housing Estate'],'government_layout','Cross River State Ministry of Housing','Odukpani',NULL,'reported',NULL,'https://www.crossriverstate.gov.ng/download/Budget/CROSS%20RIVER%20STATE%202026%20APPROVED%20BUDGET.pdf','source_found','Named in the official 2025/2026 budget, including a 2026 allocation; exact locality, tenure and site extent are not stated.',1,'Fast-growing Calabar fringe makes an unresolved government housing acquisition particularly exposed to conflicting sales.'),
 ('crs-asset-yala-vulnerable-social-housing','Yala 1,000-unit social housing scheme',ARRAY['1,000 units Social Housing for the vulnerable'],'government_layout','Cross River State Ministry of Housing','Yala',NULL,'reported',NULL,'https://www.crossriverstate.gov.ng/download/Budget/CROSS%20RIVER%20STATE%202026%20APPROVED%20BUDGET.pdf','source_found','Separately named and funded in the official budget with recorded 2025 performance; no town, site plan or land schedule is supplied.',2,'A large housing programme implies a land holding, but it must not be merged with another Yala housing project without evidence.'),
 ('crs-asset-yala-rent-to-own-housing','Yala 500-unit rent-to-own housing scheme',ARRAY['500 Rent to own low cost social housing scheme for Civil/Public Servants'],'government_layout','Cross River State Ministry of Housing','Yala',NULL,'reported',NULL,'https://www.crossriverstate.gov.ng/download/Budget/CROSS%20RIVER%20STATE%202026%20APPROVED%20BUDGET.pdf','source_found','Separately named and funded in the official budget with recorded 2025 performance; no town, site plan or land schedule is supplied.',2,'Separate programme identity is retained until evidence proves whether it shares a site with another Yala scheme.'),
 ('crs-asset-adiabo-womens-housing','Adiabo federal women''s housing scheme land',ARRAY['Adiabo women housing scheme','Family Homes Funds Adiabo site'],'government_layout','Cross River State Government / Family Homes Funds','Odukpani','Adiabo','reported',310000::numeric,'https://news.crossriverstate.gov.ng/c-river-govt-hands-over-31-hectares-of-land-to-firm-for-fg-womens-housing-scheme/','source_found','Official state report records handover of 31 hectares for a 70-unit federal women''s housing scheme; it publishes no survey plan or coordinates.',1,'A named 31-hectare government-backed housing site on the Calabar fringe has direct overlap and fraudulent-sale relevance.'),
 ('crs-asset-ogoja-gra-crown-land','Crown Land in Ogoja GRA',ARRAY['Ogoja GRA Crown Land'],'government_layout','Cross River State Ministry of Lands','Ogoja','Ogoja GRA','acquired',NULL,'https://news.crossriverstate.gov.ng/cross-river-asset-recovery-team-beams-searchlight-on-encroached-lands-in-ogoja/','source_found','Official state report identifies Crown Land in GRA among Ogoja government properties inspected for massive encroachment.',1,'The state expressly reports unlawful occupation, making this a direct priority for fraud and overlap checks once mapped.')
)
INSERT INTO provenance.spatial_asset_inventory(
 campaign_id,external_key,asset_name,alternate_names,asset_class,authority_name,country_code,admin_level_1,admin_level_2,locality,legal_status,stated_area_sqm,source_url,acquisition_status,evidence_notes,risk_priority,risk_reason,
 missing_material,next_action,processing_status,visibility
)
SELECT c.id,a.external_key,a.asset_name,a.alternate_names,a.asset_class,a.authority_name,'NG','Cross River',a.admin_level_2,a.locality,a.legal_status,a.stated_area_sqm,a.source_url,a.acquisition_status,a.evidence_notes,a.risk_priority,a.risk_reason,
 'Acquisition instrument, approved layout/site plan, allocation schedule and validated boundary geometry','Keep queued until statewide inventory closes; then acquire and validate this asset alone in priority order.','queued','public'
FROM assets a JOIN provenance.spatial_acquisition_campaigns c ON c.external_key='ng-cross-river-spatial-rerun-v1'
ON CONFLICT(external_key) DO NOTHING;

-- Down Migration
-- Inventory records are retained as research provenance.
