-- Up Migration
CREATE TABLE accounts.organizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text NOT NULL UNIQUE,status text NOT NULL DEFAULT 'active' CHECK(status IN('active','suspended','closed')),created_by_user_id uuid NOT NULL REFERENCES accounts.users(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts.role_permissions(role text NOT NULL,permission text NOT NULL,PRIMARY KEY(role,permission));
INSERT INTO accounts.role_permissions(role,permission) VALUES
('owner','organization.manage'),('owner','members.manage'),('owner','resources.manage'),('owner','billing.manage'),('owner','records.view'),
('administrator','members.manage'),('administrator','resources.manage'),('administrator','records.view'),
('case_manager','resources.manage'),('case_manager','records.view'),('reviewer','records.view'),('billing','billing.manage'),('read_only','records.view');
CREATE TABLE accounts.organization_memberships(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES accounts.organizations(id) ON DELETE RESTRICT,user_id uuid NOT NULL REFERENCES accounts.users(id) ON DELETE RESTRICT,role text NOT NULL CHECK(role IN('owner','administrator','case_manager','reviewer','billing','read_only')),status text NOT NULL DEFAULT 'active' CHECK(status IN('active','suspended','left')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,user_id));
CREATE TABLE accounts.organization_invitations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES accounts.organizations(id) ON DELETE RESTRICT,email_normalized text NOT NULL,role text NOT NULL CHECK(role IN('administrator','case_manager','reviewer','billing','read_only')),token_hash text NOT NULL UNIQUE,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','accepted','revoked','expired')),invited_by_user_id uuid NOT NULL REFERENCES accounts.users(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,accepted_at timestamptz);
ALTER TABLE registry.plots ADD COLUMN owner_organization_id uuid REFERENCES accounts.organizations(id) ON DELETE RESTRICT,ADD CONSTRAINT plots_one_owner CHECK(owner_user_id IS NULL OR owner_organization_id IS NULL);
ALTER TABLE registry.ownership_notices ADD COLUMN owner_organization_id uuid REFERENCES accounts.organizations(id) ON DELETE RESTRICT,ADD CONSTRAINT notices_one_owner CHECK(owner_user_id IS NULL OR owner_organization_id IS NULL);
ALTER TABLE registry.evidence_reports ADD COLUMN owner_organization_id uuid REFERENCES accounts.organizations(id) ON DELETE RESTRICT,ADD CONSTRAINT reports_one_owner CHECK(owner_user_id IS NULL OR owner_organization_id IS NULL);
CREATE TABLE accounts.resource_ownership_events(id bigserial PRIMARY KEY,resource_type text NOT NULL CHECK(resource_type IN('plot','ownership_notice','evidence_report')),resource_id uuid NOT NULL,from_user_id uuid,from_organization_id uuid,to_user_id uuid,to_organization_id uuid,actor_user_id uuid NOT NULL REFERENCES accounts.users(id) ON DELETE RESTRICT,reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
-- Down Migration
DROP TABLE accounts.resource_ownership_events;ALTER TABLE registry.evidence_reports DROP CONSTRAINT reports_one_owner,DROP COLUMN owner_organization_id;ALTER TABLE registry.ownership_notices DROP CONSTRAINT notices_one_owner,DROP COLUMN owner_organization_id;ALTER TABLE registry.plots DROP CONSTRAINT plots_one_owner,DROP COLUMN owner_organization_id;DROP TABLE accounts.organization_invitations;DROP TABLE accounts.organization_memberships;DROP TABLE accounts.role_permissions;DROP TABLE accounts.organizations;
